"""
Stage 0-1: Load the 100K SFT dataset with dask, introspect its actual schema
(don't hardcode column names — the OpenThoughts-Agent ladder datasets share
a family schema but you want to assert it, not assume it), then collapse
each row down to a "task spec": the part of the row that defines the task,
stripped of the specific rollout/trajectory.

Why we separate "task" from "trajectory":
Your augmentation strategy is "same tasks, new rollouts" — so the only thing
we carry forward into generation is the task definition. The trajectory
columns (turns, tool calls, final response) get regenerated by the teacher
model in stage 2/3.
"""
import json
import dask.dataframe as dd
import pandas as pd

SRC = "hf://datasets/open-thoughts/OpenThoughts-Agent-SFT-100K/data/train-*-of-*.parquet"

# Columns that typically define a *task* in this dataset family (instruction +
# environment), vs columns that define a *rollout* (the trajectory itself).
# CONFIRM against your actual schema printout below before trusting this list —
# different rungs of the scaling ladder (TaskTrove vs AgentTrove sourced rows)
# may name things slightly differently.
CANDIDATE_TASK_COLS = [
    "task_id", "id", "uuid",
    "instruction", "prompt", "task_description", "system_prompt",
    "environment", "dockerfile", "setup_script",
    "verifier", "test", "tests",
    "source", "data_source", "task_source",
]
CANDIDATE_TRAJECTORY_COLS = [
    "messages", "conversations", "trajectory", "turns",
    "completion", "response", "final_answer",
]


def inspect_schema(df: dd.DataFrame) -> None:
    print("=== dtypes ===")
    print(df.dtypes)
    print("\n=== sample row (first partition, first record) ===")
    sample = df.head(1)
    for col in sample.columns:
        val = sample.iloc[0][col]
        preview = json.dumps(val, default=str)[:300] if not isinstance(val, str) else val[:300]
        print(f"--- {col} ---\n{preview}\n")


def split_task_and_trajectory(df: dd.DataFrame) -> tuple[list[str], list[str]]:
    cols = set(df.columns)
    task_cols = [c for c in CANDIDATE_TASK_COLS if c in cols]
    traj_cols = [c for c in CANDIDATE_TRAJECTORY_COLS if c in cols]
    leftover = cols - set(task_cols) - set(traj_cols)
    print(f"Task columns found:       {task_cols}")
    print(f"Trajectory columns found: {traj_cols}")
    print(f"Unclassified columns:     {sorted(leftover)}  <- inspect these manually")
    return task_cols, traj_cols


def build_task_table(df: dd.DataFrame, task_cols: list[str]) -> dd.DataFrame:
    """Dedup-friendly task table: one row per unique task, regardless of how
    many trajectory variants currently exist for it in the source data."""
    keep = [c for c in task_cols if c in df.columns]
    tasks = df[keep].drop_duplicates(subset=[c for c in keep if c in ("task_id", "id", "uuid")] or keep)
    return tasks


if __name__ == "__main__":
    df = dd.read_parquet(SRC)
    print(f"Partitions: {df.npartitions}, approx rows: {len(df)}")
    inspect_schema(df)
    task_cols, traj_cols = split_task_and_trajectory(df)

    tasks = build_task_table(df, task_cols)
    tasks.to_parquet("~/pipeline/data/tasks/", write_index=False)
    print(f"Wrote task table -> ~/pipeline/data/tasks/")
